version: "3.8"
services:
  hugo:
    image: hugo_ergo
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 384M
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    networks:
      - hugonet
    ports:
      - "0.0.0.0:3113:1313"
    restart: unless-stopped
    entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      - /etc/letsencrypt/live/portfolio.terminaldweller.com/privkey.pem:/etc/letsencrypt/live/portfolio.terminaldweller.com/privkey.pem:ro
      - /etc/letsencrypt/live/portfolio.terminaldweller.com/fullchain.pem:/etc/letsencrypt/live/portfolio.terminaldweller.com/fullchain.pem:ro
networks:
  hugonet:
